[package]
name = "moma_conways_game_of_life"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
moma = "0.3.0"
moma_simulation_engine = "0.1.7"
pixels = "0.13.0"
winit = "0.29.0"
rand_chacha = "0.3.1"
winit_input_helper = "0.16.0"
