[package]
name = "moma_gower"
version = "0.2.1"
edition = "2024"
authors = ["Neil Crago"]

[dependencies]
moma = "0.3.2"
moma_simulation_engine = "0.2.1"
pixels = "0.13.0"
rand = "0.9.2"
rustfft = "6.4.0"
winit = "0.28.6"
winit_input_helper = "0.14.1"
