[package]
name = "moma_dynamic_pathfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
moma = "0.3.2"
moma_simulation_engine = "0.1.7"
pixels = "0.13.0"
winit = "0.28.6" # Downgraded from 0.29
winit_input_helper = "0.14.1" # Use a version compatible with winit 0.28